
name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create config.ini
      run: |
        echo "[settings]" > config.ini
        echo "base_url = https://moneydd-dev.thinkerfint.com" >> config.ini
        echo "email = ${{ secrets.TEST_EMAIL }}" >> config.ini
        echo "password = ${{ secrets.TEST_PASSWORD }}" >> config.ini
    - name: Test with pytest
      run: |
        pytest -n auto --tb=short
